### ISSUE TITLE
Keras callback error and model config ‘NoneType’ after training

### ISSUE THREAD

**Issue by SoyGema** [SoyGema/The-Lord-of-The-Words-The-two-frameworks#3]
Posted in [forum,](https://discuss.huggingface.co/t/keras-callback-error-and-model-config-nonetype-after-training/47091/1) but will follow backtrace here

**Comment by SoyGema** [comment]
Error traceback

```
Traceback (most recent call last):
  File "/Users/gema/Documents/The-Lord-of-The-Words-The-two-frameworks/src/models/train_model.py", line 742, in <module>
    main()
  File "/Users/gema/Documents/The-Lord-of-The-Words-The-two-frameworks/src/models/train_model.py", line 695, in main
    history = model.fit(tf_train_dataset, epochs=int(training_args.num_train_epochs), callbacks=callbacks)
  File "/Users/gema/Documents/The-Lord-of-The-Words-The-two-frameworks/.venv3.9/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/Users/gema/Documents/transformers/src/transformers/keras_callbacks.py", line 225, in on_epoch_end
    predictions = self.model.generate(
  File "/Users/gema/Documents/transformers/src/transformers/generation/tf_utils.py", line 853, in generate
    and generation_config.min_length > generation_config.max_length
TypeError: '>' not supported between instances of 'int' and 'NoneType'
```
Hypothesis:
The error seems to be when we call the prediction, as it is in the folder `/generation` . In utils.py seems to say when the code breaks

> 
```python
        # If the input length is a tensor (i.e. dynamic length), skip length checks
        if not isinstance(input_ids_seq_length, tf.Tensor):
            if (
                generation_config.min_length is not None
                and generation_config.min_length > generation_config.max_length
            ):
                raise ValueError(
                    f"Unfeasable length constraints: the minimum length ({generation_config.min_length}) is larger"
                    f" than the maximum length ({generation_config.max_length})"
                )```

**Comment by SoyGema** [comment]
Solved in https://github.com/SoyGema/The-Lord-of-The-Words-The-two-frameworks/commit/7c1dfeb757ce96b4a636eb4db8e99e2f4698378e 
Issue was related to the `max_target_length` of the prediction dataset, that was by default set to `None`
