### ISSUE TITLE
[num_beams] TypeError: '>' not supported between instances of 'NoneType' and 'int' 

### ISSUE THREAD

**Issue by SoyGema** [SoyGema/The-Lord-of-The-Words-The-two-frameworks#4]
Error trace 
```
Traceback (most recent call last):
  File "/Users/gema/Documents/The-Lord-of-The-Words-The-two-frameworks/src/models/train_model.py", line 742, in <module>
    main()
  File "/Users/gema/Documents/The-Lord-of-The-Words-The-two-frameworks/src/models/train_model.py", line 695, in main
    history = model.fit(tf_train_dataset, epochs=int(training_args.num_train_epochs), callbacks=callbacks)
  File "/Users/gema/Documents/The-Lord-of-The-Words-The-two-frameworks/.venv3.9/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/Users/gema/Documents/transformers/src/transformers/keras_callbacks.py", line 225, in on_epoch_end
    predictions = self.model.generate(
  File "/Users/gema/Documents/transformers/src/transformers/generation/tf_utils.py", line 882, in generate
    and (generation_config.num_beams > 1)
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

**Comment by SoyGema** [comment]
Solved in https://github.com/SoyGema/The-Lord-of-The-Words-The-two-frameworks/commit/1131ecaa4996896e40ac7e6c5d9b63d2ac98812b . Change parameter
